### ISSUE TITLE
最后一步报错

### ISSUE THREAD

**Issue by rover75** [tbc0309/Portainer-CN2021#1]
大佬，我执行最后一步命令：docker run -d -p 9000:9000 --name portainer --restart always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data -v /public:/public portainer/portainer时报错：
docker: Error response from daemon: AppArmor enabled on system but the docker-default profile could not be loaded: running `/usr/sbin/apparmor_parser apparmor_parser -Kr /var/lib/docker/tmp/docker-default3186881261` failed with output: apparmor_parser: Unable to replace "docker-default".  Permission denied; attempted to load a profile while confined?

请问是怎么回事？谢谢

**Comment by tbc0309** [comment]
/public:/public

前面是汉化文件夹的实际路径，你确认对吗？你放在系统根目录？
